version: '3.5'

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: showcase
      POSTGRES_USER: app
      POSTGRES_PASSWORD: SuperSecurePassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432