version: '3.5'

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
      args: ["TRG_ENV=prod", "PG_HOST=pg"]
    environment:
      PG_HOST: pg
      TRG_ENV: prod
    volumes:
    - ./ship-showdown:/app
    ports:
      - 5000:5000
    depends_on:
      - pg

  